package org.rokz.lotmMc;

public enum PathwaySequence {

 // ───────── Lord of Mysteries ─────────
 SEER_9, SEER_8, SEER_7, SEER_6, SEER_5, SEER_4, SEER_3, SEER_2, SEER_1, SEER_0,
 
 APPRENTICE_9, APPRENTICE_8, APPRENTICE_7, APPRENTICE_6, APPRENTICE_5,
 APPRENTICE_4, APPRENTICE_3, APPRENTICE_2, APPRENTICE_1, APPRENTICE_0,
 
 MARAUDER_9, MARAUDER_8, MARAUDER_7, MARAUDER_6, MARAUDER_5,
 MARAUDER_4, MARAUDER_3, MARAUDER_2, MARAUDER_1, MARAUDER_0,

 // ───────── God Almighty ─────────
 SPECTATOR_9, SPECTATOR_8, SPECTATOR_7, SPECTATOR_6, SPECTATOR_5,
 SPECTATOR_4, SPECTATOR_3, SPECTATOR_2, SPECTATOR_1, SPECTATOR_0,
 
 BARD_9, BARD_8, BARD_7, BARD_6, BARD_5,
 BARD_4, BARD_3, BARD_2, BARD_1, BARD_0,
 
 SAILOR_9, SAILOR_8, SAILOR_7, SAILOR_6, SAILOR_5,
 SAILOR_4, SAILOR_3, SAILOR_2, SAILOR_1, SAILOR_0,
 
 READER_9, READER_8, READER_7, READER_6, READER_5,
 READER_4, READER_3, READER_2, READER_1, READER_0,
 
 SECRET_9, SECRET_8, SECRET_7, SECRET_6, SECRET_5,
 SECRET_4, SECRET_3, SECRET_2, SECRET_1, SECRET_0,

 // ───────── Eternal Darkness ─────────
 SLEEPLESS_9, SLEEPLESS_8, SLEEPLESS_7, SLEEPLESS_6, SLEEPLESS_5,
 SLEEPLESS_4, SLEEPLESS_3, SLEEPLESS_2, SLEEPLESS_1, SLEEPLESS_0,

 CORPSE_9, CORPSE_8, CORPSE_7, CORPSE_6, CORPSE_5,
 CORPSE_4, CORPSE_3, CORPSE_2, CORPSE_1, CORPSE_0,

 WARRIOR_9, WARRIOR_8, WARRIOR_7, WARRIOR_6, WARRIOR_5,
 WARRIOR_4, WARRIOR_3, WARRIOR_2, WARRIOR_1, WARRIOR_0,

 // ───────── Calamity of Destruction ─────────
 HUNTER_9, HUNTER_8, HUNTER_7, HUNTER_6, HUNTER_5,
 HUNTER_4, HUNTER_3, HUNTER_2, HUNTER_1, HUNTER_0,

 ASSASSIN_9, ASSASSIN_8, ASSASSIN_7, ASSASSIN_6, ASSASSIN_5,
 ASSASSIN_4, ASSASSIN_3, ASSASSIN_2, ASSASSIN_1, ASSASSIN_0,

 // ───────── Demon of Knowledge ─────────
 SAVANT_9, SAVANT_8, SAVANT_7, SAVANT_6, SAVANT_5,
 SAVANT_4, SAVANT_3, SAVANT_2, SAVANT_1, SAVANT_0,

 MYSTERY_9, MYSTERY_8, MYSTERY_7, MYSTERY_6, MYSTERY_5,
 MYSTERY_4, MYSTERY_3, MYSTERY_2, MYSTERY_1, MYSTERY_0,

 // ───────── Key of Light ─────────
 MONSTER_9, MONSTER_8, MONSTER_7, MONSTER_6, MONSTER_5,
 MONSTER_4, MONSTER_3, MONSTER_2, MONSTER_1, MONSTER_0,

 // ───────── Goddess of Origin ─────────
 PLANTER_9, PLANTER_8, PLANTER_7, PLANTER_6, PLANTER_5,
 PLANTER_4, PLANTER_3, PLANTER_2, PLANTER_1, PLANTER_0,

 APOTHECARY_9, APOTHECARY_8, APOTHECARY_7, APOTHECARY_6, APOTHECARY_5,
 APOTHECARY_4, APOTHECARY_3, APOTHECARY_2, APOTHECARY_1, APOTHECARY_0,

 // ───────── Father of Devils ─────────
 PRISONER_9, PRISONER_8, PRISONER_7, PRISONER_6, PRISONER_5,
 PRISONER_4, PRISONER_3, PRISONER_2, PRISONER_1, PRISONER_0,

 CRIMINAL_9, CRIMINAL_8, CRIMINAL_7, CRIMINAL_6, CRIMINAL_5,
 CRIMINAL_4, CRIMINAL_3, CRIMINAL_2, CRIMINAL_1, CRIMINAL_0,

 // ───────── The Anarchy ─────────
 LAWYER_9, LAWYER_8, LAWYER_7, LAWYER_6, LAWYER_5,
 LAWYER_4, LAWYER_3, LAWYER_2, LAWYER_1, LAWYER_0,

 ARBITER_9, ARBITER_8, ARBITER_7, ARBITER_6, ARBITER_5,
 ARBITER_4, ARBITER_3, ARBITER_2, ARBITER_1, ARBITER_0,

 RESETER_0
}
